# Generated by Django 4.0.3 on 2022-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('entrada', models.DateTimeField(blank=True, null=True)),
                ('comida', models.DateTimeField(blank=True, null=True)),
                ('llegada', models.DateTimeField(blank=True, null=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
